/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
"use strict";
var IAccount;
(function (IAccount) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Savings"] = 'Savings'] = "Savings";
        TypeEnum[TypeEnum["Loan"] = 'Loan'] = "Loan";
        TypeEnum[TypeEnum["CreditCard"] = 'CreditCard'] = "CreditCard";
    })(TypeEnum = IAccount.TypeEnum || (IAccount.TypeEnum = {}));
})(IAccount = exports.IAccount || (exports.IAccount = {}));
