/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface IAccount {
    id?: string;

    type?: IAccount.TypeEnum;

    name?: string;

    balance?: number;

    transactions?: Array<models.ITransaction>;

}
export namespace IAccount {
    export enum TypeEnum {
        Savings = <any> 'Savings',
        Loan = <any> 'Loan',
        CreditCard = <any> 'CreditCard'
    }
}
