/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
"use strict";
var IRecurrence;
(function (IRecurrence) {
    var FrequencyEnum;
    (function (FrequencyEnum) {
        FrequencyEnum[FrequencyEnum["Weekly"] = 'Weekly'] = "Weekly";
        FrequencyEnum[FrequencyEnum["BiWeekly"] = 'BiWeekly'] = "BiWeekly";
        FrequencyEnum[FrequencyEnum["Monthly"] = 'Monthly'] = "Monthly";
        FrequencyEnum[FrequencyEnum["Annually"] = 'Annually'] = "Annually";
    })(FrequencyEnum = IRecurrence.FrequencyEnum || (IRecurrence.FrequencyEnum = {}));
})(IRecurrence = exports.IRecurrence || (exports.IRecurrence = {}));
//# sourceMappingURL=IRecurrence.js.map