/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface IRecurrence {
    frequency?: IRecurrence.FrequencyEnum;

    dayOfMonth?: number;

    dayOfWeek?: string;

    week?: number;

}
export namespace IRecurrence {
    export enum FrequencyEnum {
        Weekly = <any> 'Weekly',
        BiWeekly = <any> 'BiWeekly',
        Monthly = <any> 'Monthly',
        Annually = <any> 'Annually'
    }
}
