/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
"use strict";
var ITransaction;
(function (ITransaction) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Deposit"] = 'Deposit'] = "Deposit";
        TypeEnum[TypeEnum["Fee"] = 'Fee'] = "Fee";
        TypeEnum[TypeEnum["Withdrawal"] = 'Withdrawal'] = "Withdrawal";
        TypeEnum[TypeEnum["Transfer"] = 'Transfer'] = "Transfer";
    })(TypeEnum = ITransaction.TypeEnum || (ITransaction.TypeEnum = {}));
})(ITransaction = exports.ITransaction || (exports.ITransaction = {}));
//# sourceMappingURL=ITransaction.js.map