/**
 * BankAppApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ITransaction {
    id?: string;

    accountId?: string;

    type?: ITransaction.TypeEnum;

    description?: string;

    amount?: number;

    postDate?: Date;

}
export namespace ITransaction {
    export enum TypeEnum {
        Deposit = <any> 'Deposit',
        Fee = <any> 'Fee',
        Withdrawal = <any> 'Withdrawal',
        Transfer = <any> 'Transfer'
    }
}
